apiVersion: v2
appVersion: "1.0"
description: A Helm chart for civil-general-apps-ccd-definition App
name: civil-general-apps-ccd-definition
home: https://github.com/hmcts/civil-general-apps-ccd-definition
version: 0.0.1
maintainers:
  - name: HMCTS civil team
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
