civil-general-applications:
  java:
    ingressHost: ${SERVICE_FQDN}
    keyVaults:
      civil:
        resourceGroup: civil
        secrets:
          - civil-idam-client-secret
          - microservicekey-civil-service
          - system-update-user-username
          - system-update-user-password
          - cross-access-user-username
          - cross-access-user-password
          - prd-admin-user-username
          - prd-admin-user-password
          - name: AppInsightsInstrumentationKeyGeneralApplications
            alias: azure.application-insights.instrumentation-key
          - docmosis-api-key
          - gov-notify-api-key
          - sendgrid-api-key
          - robotics-notification-sender
          - robotics-notification-recipient
          - name: launch-darkly-sdk-key-non-prod
            alias: launch-darkly-sdk-key
          - robotics-notification-multipartyrecipient
      civil-gen-apps:
        resourceGroup: civil
        secrets:
          - microservicekey-civil-general-applications
    environment:
      LAUNCH_DARKLY_ENV: service-staging
      PAY_CALLBACK_URL: https://civil-ga-ccd-staging.aat.platform.hmcts.net/service-request-update
civil-service:
  java:
    ingressHost: civil-ga-ccd-civil-service-staging.aat.platform.hmcts.net
    keyVaults:
      civil:
        resourceGroup: civil
        secrets:
          - civil-idam-client-secret
          - microservicekey-civil-service
          - system-update-user-username
          - system-update-user-password
          - cross-access-user-username
          - cross-access-user-password
          - prd-admin-user-username
          - prd-admin-user-password
          #- AppInsightsInstrumentationKey needs to be replaced with GA specific key
          - docmosis-api-key
          - gov-notify-api-key
          - sendgrid-api-key
          - robotics-notification-sender
          - robotics-notification-recipient
          - name: launch-darkly-sdk-key-non-prod
            alias: launch-darkly-sdk-key
          - ordnance-survey-api-key
          - robotics-notification-multipartyrecipient
          - name: robotics-notification-recipient-spec
            alias: robotics.notification.specRecipient
    environment:
      LAUNCH_DARKLY_ENV: ${SERVICE_FQDN}
idam-pr:
  redirect_uris:
    XUI:
      - https://civil-ga-ccd-xui-staging.aat.platform.hmcts.net/oauth2/callback
xui-webapp:
  nodejs:
    ingressHost: civil-ga-ccd-xui-staging.aat.platform.hmcts.net
ccd:
  ccd-api-gateway-web:
    nodejs:
      ingressHost: civil-ga-ccd-gateway-staging.aat.platform.hmcts.net
  ccd-data-store-api:
    java:
      ingressHost: civil-ga-ccd-data-store-staging.aat.platform.hmcts.net
  ccd-definition-store-api:
    java:
      ingressHost: civil-ga-ccd-definition-store-staging.aat.platform.hmcts.net
camunda-bpm:
  java:
    ingressHost: civil-ga-ccd-camunda-staging.aat.platform.hmcts.net
civil-wa:
  enabled: false
postgresql:
  enabled: false
